### ISSUE TITLE
add LICENSE file

### ISSUE THREAD

**Issue by waldenn** [Dorialexander/UniversalAlmanac#1]
Cool idea with many possibilities. Thanks!

**Comment by Dorialexander** [comment]
Done. Thanks a lot for your interest!

**Comment by waldenn** [comment]
Ok, great. I've made my own iframe-embedded integration with it [code here](https://github.com/waldenn/UniversalAlmanac). You can see the app linked from [here](https://conze.pt/explore/2019%20Swiss%20federal%20election?l=en&t=dates&s=true) using the "day" icon-links.

At some later stage I might write a JS version (without PHP) using the wikibase library, as I think that would be more suited for my project.

Perhaps an interesting library for adding year / month / week / short-date-range calender overviews (with links to the days) is [year-calendar](https://year-calendar.github.io/js-year-calendar/examples).

**Comment by Dorialexander** [comment]
Oh that's great! Yes my experience in web development is fairly old-fashioned (that's why I kept the app layout simple and straightforward for the moment). I really like the idea of adding the calendar. For the time being my main objective would be to include the events specified inside a qualifier (for instance start date for a person holding an office) but the SPARQL query is not easy to build.

**Comment by waldenn** [comment]
Thank you. Looking forward to the updates! Its an inspiring idea, no matter what the implementation is.
